name: raster_ai
description: "Image generator with AI agent"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.6.1
  http: ^1.3.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  web_socket_channel: ^3.0.2
  logging: ^1.3.0
  flutter_native_splash: ^2.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3


flutter:
  uses-material-design: true

  assets:
    - images/logo.png

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "images/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "images/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  macos:
    generate: true
    image_path: "images/logo.png"

flutter_native_splash:
  color: "#9baab1"
  image: images/logo.png
  android: true
  ios: true
  web: true